# Generated by Django 4.2 on 2023-08-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaming", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="price_cente",
        ),
        migrations.AddField(
            model_name="game",
            name="price",
            field=models.FloatField(default=3799.94),
        ),
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.URLField(max_length=500),
        ),
    ]
