# Generated by Django 4.2 on 2023-08-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaming", "0002_remove_game_price_cente_game_price_alter_game_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="price",
            new_name="price_cente",
        ),
        migrations.AddField(
            model_name="game",
            name="description1",
            field=models.TextField(
                default="RTX 3080 Max-Q Ampere Côté carte graphique,avec l'architecture Ampere de sa RTX 3080 (8 Go DDR6), NVIDIA ne se contente pas seulement de proposer un gain de performances conséquent par rapport à la génération précédente, mais en a également profité pour grandement améliorer les technologies RTX ainsi que le rendement et le nombre des coeurs RT et Tenseurs, unités de calcul dédiées respectivement au ray tracing (qui permet de simuler le comportement physique de la lumière pour un rendu cinématographique) et à l'assistance au rendu graphique 3D via le Deep Learning super Sample (DLSS). Les résultats ? Plus de fluidité et une réduction de l'impact du ray-tracing sur le nombre de frame.€\n\n",
                max_length=10000,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="description2",
            field=models.TextField(
                default="RTX 3080 Max-Q Ampere Côté carte graphique,avec l'architecture Ampere de sa RTX 3080 (8 Go DDR6), NVIDIA ne se contente pas seulement de proposer un gain de performances conséquent par rapport à la génération précédente, mais en a également profité pour grandement améliorer les technologies RTX ainsi que le rendement et le nombre des coeurs RT et Tenseurs, unités de calcul dédiées respectivement au ray tracing (qui permet de simuler le comportement physique de la lumière pour un rendu cinématographique) et à l'assistance au rendu graphique 3D via le Deep Learning super Sample (DLSS). Les résultats ? Plus de fluidité et une réduction de l'impact du ray-tracing sur le nombre de frame.€\n\n",
                max_length=10000,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="description3",
            field=models.TextField(
                default="RTX 3080 Max-Q Ampere Côté carte graphique,avec l'architecture Ampere de sa RTX 3080 (8 Go DDR6), NVIDIA ne se contente pas seulement de proposer un gain de performances conséquent par rapport à la génération précédente, mais en a également profité pour grandement améliorer les technologies RTX ainsi que le rendement et le nombre des coeurs RT et Tenseurs, unités de calcul dédiées respectivement au ray tracing (qui permet de simuler le comportement physique de la lumière pour un rendu cinématographique) et à l'assistance au rendu graphique 3D via le Deep Learning super Sample (DLSS). Les résultats ? Plus de fluidité et une réduction de l'impact du ray-tracing sur le nombre de frame.€\n\n",
                max_length=10000,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="game",
            name="os_langage",
            field=models.CharField(default="français", max_length=200),
        ),
    ]
