# Generated by Django 4.2 on 2023-08-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaming", "0003_rename_price_game_price_cente_game_description1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="description1",
        ),
        migrations.RemoveField(
            model_name="game",
            name="description2",
        ),
        migrations.RemoveField(
            model_name="game",
            name="description3",
        ),
        migrations.AddField(
            model_name="game",
            name="descriptions",
            field=models.TextField(default="cool", max_length=10000),
        ),
    ]
