# Generated by Django 4.2 on 2023-08-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaming", "0004_remove_game_description1_remove_game_description2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="descriptions1",
            field=models.TextField(default="cool", max_length=10000),
        ),
        migrations.AddField(
            model_name="game",
            name="descriptions2",
            field=models.TextField(default="cool", max_length=10000),
        ),
    ]
