# Generated by Django 4.2 on 2023-08-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaming", "0005_game_descriptions1_game_descriptions2"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="titre",
            field=models.CharField(
                default="La station de travail CreatorPro X17 A12UKS-080FR a un objectif simple : vous donner suffisamment de puissance pour réaliser tous vos projets. Carte graphique NVIDIA RTX Quadro, processeur Intel Alder Lake HX, dalle Ultra HD 120 Hz...elle ne lésine pas sur les moyens pour atteindre ses objectifs.",
                max_length=500,
            ),
        ),
    ]
